import process from "node:process";
import z from "zod";

export const PRODUCTION = process.env.NODE_ENV === "production";

const messageLogChannelIdsSchema = z
	.string()
	.min(2)
	.transform((arg, ctx) => {
		try {
			return JSON.parse(arg);
		} catch {
			ctx.addIssue({ code: "custom", message: "Invalid JSON format.", input: arg });
			return z.NEVER;
		}
	})
	.pipe(z.array(z.string()).readonly());

const envSchema = z.object({
	DISCORD_TOKEN: z.string().min(1),
	APPLICATION_ID: z.string().min(1),
	GUILD_ID: z.string().min(1),
	RAW_AFFILIATES_CHANNEL_ID: z.string().min(1),
	AFFILIATES_CHANNEL_ID: z.string().min(1),
	SOULOBBY_MAIL_CHANNEL_ID: z.string().min(1),
	OVERVIEW_CHANNEL_ID: z.string().min(1),
	CALLS_VIEW_CHANNEL_ID: z.string().min(1),
	CALLS_CHANNEL_ID: z.string().min(1),
	DAILY_CAT_CHANNEL_ID: z.string().min(1),
	CORRUPTED_EGG_QUEUE_CHANNEL_ID: z.string().min(1),
	CORRUPTED_HELP_CHANNEL_ID: z.string().min(1),
	CORRUPTED_EGG_LOG_CHANNEL_ID: z.string().min(1),
	CORRUPTED_VIEW_CHANNEL_ID: z.string().min(1),
	QUEUE_VIEW_CHANNEL_ID: z.string().min(1),
	QUEUE_CHAT_CHANNEL_ID: z.string().min(1),
	CORRUPTED_ARCHIVE_CHANNEL_ID: z.string().min(1),
	FRIENDS_LIST_CHANNEL_ID: z.string().min(1),
	GAME_CASES_CHANNEL_ID: z.string().min(1),
	DISCORD_CASES_CHANNEL_ID: z.string().min(1),
	EX_FRIENDS_LIST_CHANNEL_ID: z.string().min(1),
	EX_IGNORE_LIST_CHANNEL_ID: z.string().min(1),
	TOPICS_CHANNEL_ID: z.string().min(1),
	SOULOBBY_LOG_CHANNEL_ID: z.string().min(1),
	MEMBER_LOG_CHANNEL_ID: z.string().min(1),
	MESSAGE_LOG_EXPLICIT_ALLOWED_CHANNEL_IDS: messageLogChannelIdsSchema,
	MESSAGE_LOG_EXPLICIT_DISALLOWED_CHANNEL_IDS: messageLogChannelIdsSchema,
	QUEUE_LOG_CHANNEL_ID: z.string().min(1),
	QUICK_QUIZ_LOG_CHANNEL_ID: z.string().min(1),
	REPORT_TAG_ID: z.string().min(1),
	GENERAL_ROLE_ID: z.string().min(1),
	CAPTAIN_ROLE_ID: z.string().min(1),
	STAR_RANK_ROLE_ID: z.string().min(1),
	RANK_ROLE_ID: z.string().min(1),
	SMILEY_ROLE_ID: z.string().min(1),
	QUEUE_HELPER_ROLE_ID: z.string().min(1),
	SANDY_ROLE_ID: z.string().min(1),
	EX_RANK_ROLE_ID: z.string().min(1),
	LUCIFURR_ROLE_ID: z.string().min(1),
	TAKHUIT_ROLE_ID: z.string().min(1),
	FENEKH_ROLE_ID: z.string().min(1),
	NODJMET_ROLE_ID: z.string().min(1),
	BLANCHY_ROLE_ID: z.string().min(1),
	HETEPHERES_ROLE_ID: z.string().min(1),
	LEARNER_ROLE_ID: z.string().min(1),
	MESSAGE_LOG_WEBHOOK_ID: z.string().min(1),
	MESSAGE_LOG_WEBHOOK_TOKEN: z.string().min(1),
	OVERVIEW1_MESSAGE_ID: z.string().min(1),
	CALLS_VIEW1_MESSAGE_ID: z.string().min(1),
	CORRUPTED_VIEW1_MESSAGE_ID: z.string().min(1),
	QUEUE_CHAT1_MESSAGE_ID: z.string().min(1),
	QUEUE_CHAT2_MESSAGE_ID: z.string().min(1),
	FRIENDS_LIST1_MESSAGE_ID: z.string().min(1),
	DATABASE_URL: z.string().min(1),
	CDN_BUCKET: z.string().min(1),
	CDN_URL: z.string().min(1),
	S3_ACCESS_KEY_ID: z.string().min(1),
	S3_ACCOUNT_ID: z.string().min(1),
	S3_SECRET_ACCESS_KEY: z.string().min(1),
	// Production only.
	SENTRY_DATA_SOURCE_NAME: z.string().min(1).optional(),
	SENTRY_RELEASE: z.string().min(1).optional(),
});

const productionEnvSchema = envSchema.extend({
	SENTRY_DATA_SOURCE_NAME: z.string().min(1),
	SENTRY_RELEASE: z.string().min(1),
});

export const {
	DISCORD_TOKEN,
	APPLICATION_ID,
	GUILD_ID,
	RAW_AFFILIATES_CHANNEL_ID,
	AFFILIATES_CHANNEL_ID,
	SOULOBBY_MAIL_CHANNEL_ID,
	OVERVIEW_CHANNEL_ID,
	CALLS_VIEW_CHANNEL_ID,
	CALLS_CHANNEL_ID,
	DAILY_CAT_CHANNEL_ID,
	CORRUPTED_EGG_QUEUE_CHANNEL_ID,
	CORRUPTED_HELP_CHANNEL_ID,
	CORRUPTED_EGG_LOG_CHANNEL_ID,
	CORRUPTED_VIEW_CHANNEL_ID,
	QUEUE_VIEW_CHANNEL_ID,
	QUEUE_CHAT_CHANNEL_ID,
	CORRUPTED_ARCHIVE_CHANNEL_ID,
	FRIENDS_LIST_CHANNEL_ID,
	GAME_CASES_CHANNEL_ID,
	DISCORD_CASES_CHANNEL_ID,
	EX_FRIENDS_LIST_CHANNEL_ID,
	EX_IGNORE_LIST_CHANNEL_ID,
	TOPICS_CHANNEL_ID,
	SOULOBBY_LOG_CHANNEL_ID,
	MEMBER_LOG_CHANNEL_ID,
	MESSAGE_LOG_EXPLICIT_ALLOWED_CHANNEL_IDS,
	MESSAGE_LOG_EXPLICIT_DISALLOWED_CHANNEL_IDS,
	QUEUE_LOG_CHANNEL_ID,
	QUICK_QUIZ_LOG_CHANNEL_ID,
	REPORT_TAG_ID,
	GENERAL_ROLE_ID,
	CAPTAIN_ROLE_ID,
	STAR_RANK_ROLE_ID,
	RANK_ROLE_ID,
	SMILEY_ROLE_ID,
	QUEUE_HELPER_ROLE_ID,
	SANDY_ROLE_ID,
	EX_RANK_ROLE_ID,
	LUCIFURR_ROLE_ID,
	TAKHUIT_ROLE_ID,
	FENEKH_ROLE_ID,
	NODJMET_ROLE_ID,
	BLANCHY_ROLE_ID,
	HETEPHERES_ROLE_ID,
	LEARNER_ROLE_ID,
	MESSAGE_LOG_WEBHOOK_ID,
	MESSAGE_LOG_WEBHOOK_TOKEN,
	OVERVIEW1_MESSAGE_ID,
	CALLS_VIEW1_MESSAGE_ID,
	CORRUPTED_VIEW1_MESSAGE_ID,
	QUEUE_CHAT1_MESSAGE_ID,
	QUEUE_CHAT2_MESSAGE_ID,
	FRIENDS_LIST1_MESSAGE_ID,
	DATABASE_URL,
	CDN_BUCKET,
	CDN_URL,
	S3_ACCESS_KEY_ID,
	S3_ACCOUNT_ID,
	S3_SECRET_ACCESS_KEY,
	SENTRY_DATA_SOURCE_NAME,
	SENTRY_RELEASE,
} = (PRODUCTION ? productionEnvSchema : envSchema).parse(process.env);
